### ISSUE TITLE
Snippet not working (Custom Logo)

### ISSUE THREAD

**Issue by svtcpx** [mainwp/mainwp-custom-dashboard-extension-examples#4]
Hi there,

FYI this snippet does nothing for me:

https://github.com/mainwp/mainwp-custom-dashboard-extension-examples/blob/master/css/change-dashboard-logo.css

On a side note: Rarely have I ever had less fun customizing a product I've purchased. Perhaps consider allowing your customers to add their own logo by uploading it. It's 2024 for crying out loud... ;D

Cheers

**Comment by kwcjr** [comment]
Dear User,

Thank you for bringing this to our attention so it can be addressed. These code snippets are merely "Examples" provided by either the broader community or us at MainWP as a courtesy. As they are not integral parts of MainWP Core or any of its Extensions, they are not regularly maintained. If you had taken the time to read the comments header, you would have noticed that this particular snippet was last tested on MainWP v 5.0.1, and we are currently on MainWP v 5.1. It’s fortunate that you spotted this & I have updated the CSS snippet so that it will function as intended.

![chrome_ZAQYVPhI8S](https://github.com/mainwp/mainwp-custom-dashboard-extension-examples/assets/9300827/0c3d5f97-4f44-467a-a971-080f9d616651)

If you have the skills and the inclination to contribute to MainWP’s Open Source Code, you are welcome to open a Pull Request. We are always open to collaborating with others.

We appreciate your feedback about our product. In the future, please use our dedicated feedback site at http://feedback.mainwp.com/ and share your pain points and requirements, allowing others to vote on them.

Best regards,
The MainWP Team
